version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "main"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:00"
